// <auto-generated />
using GineSys.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GineSys.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180504201609_MotivosConsultaTable")]
    partial class MotivosConsultaTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GineSys.API.Models.Aseguradora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Contacto")
                        .HasMaxLength(255);

                    b.Property<string>("Correo")
                        .HasMaxLength(255);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Fax")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("FechaCreacion");

                    b.Property<DateTime?>("FechaModificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("TelefonoFijo")
                        .HasMaxLength(20);

                    b.Property<string>("TelefonoMovil")
                        .HasMaxLength(20);

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(20);

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Aseguradoras");
                });

            modelBuilder.Entity("GineSys.API.Models.GrupoSanguineo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime?>("FechaCreacion");

                    b.Property<DateTime?>("FechaModificacion");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(20);

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("GruposSanguineos");
                });

            modelBuilder.Entity("GineSys.API.Models.MotivoConsulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime?>("FechaCreacion");

                    b.Property<DateTime?>("FechaModificacion");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(20);

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("MotivosConsulta");
                });

            modelBuilder.Entity("GineSys.API.Models.Ocupacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime?>("FechaCreacion");

                    b.Property<DateTime?>("FechaModificacion");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(20);

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Ocupaciones");
                });

            modelBuilder.Entity("GineSys.API.Models.Religion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<DateTime?>("FechaCreacion");

                    b.Property<DateTime?>("FechaModificacion");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(20);

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Religiones");
                });

            modelBuilder.Entity("GineSys.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("FechaCreacion");

                    b.Property<DateTime?>("FechaModificacion");

                    b.Property<bool>("IsAdmin");

                    b.Property<bool>("IsDoctor");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(20);

                    b.Property<string>("UsuarioMoficacion")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
